### ISSUE TITLE
Add OperativeZoneTemperature for thermal discomfort KPI calculation

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#113]
The KPI calculator uses measurement outputs with KPI ID "AirZoneTemperature" to calculate the thermal discomfort core KPI.  However, for zones served by radiant systems, it may be more appropriate to calculate thermal discomfort with the KPI ID "OperativeZoneTemperature."  A proposed solution is to edit line 110 of ``kpis/kpi_calculator.py`` (``for signal in self.case.kpi_json['AirZoneTemperature']:``) to include signals from ``self.case.kpi_json['OperativeZoneTemperature']`` as well.

**Comment by JavierArroyoBastida** [comment]
@dhblum @icupeiro my suggestion is to include both, "AirZoneTemperature" and "OperativeZoneTemperature", and give the user the possibility to choose which one to use for comfort KPI calculation.

**Comment by icupeiro** [comment]
I agree with @JavierArroyoBastida suggestion

In addition to @dhblum comment in #186 and thinking about the multizone-commercial-hydronic case, indeed the air system controls the supply air temperature, however being an hybrid GEOTABS system I find more appropiate to use the operative temperature metric (since the whole structure is activated and roof/walls effects is significant). Moreover, thermostats are usually placed against walls, so their measurement is affected to some extent by the radiant wall temperature.

**Comment by dhblum** [comment]
As described in my initial description of this issue, I believe the only change necessary would be in ``kpis/kpi_calculator.py`` where instead of just searching for ``"AirZoneTemperature"``, ``"OperativeZoneTemperature"`` is also included.  The signal exchange read block already has an option for Operative Temperature and the parser will include it in the ``kpis.json`` just like Air Temperature.
