### ISSUE TITLE
Deal with models without Overwrite blocks

### ISSUE THREAD

**Issue by SenHuang19** [ibpsa/project1-boptest#115]
This issue is to deal with models without Overwrite blocks by modifying the parse function.

**Comment by SenHuang19** [comment]
If models have no Overwrite blocks, the following error occur when parsing the model

> Unexpected token: "end wrapped"

A quick solution is to change line 157-160 of the parse

>             if i == len(instances['Overwrite'])-1:
>                 f.write(') "Original model with overwrites";\n')
>             else:
>                 f.write(',\n')

into

>             if i != len(instances['Overwrite'])-1:
>                 f.write(',\n')
>       f.write(') "Original model with overwrites";\n')

Not sure if other components have to be updated as well? @dhblum

**Comment by dhblum** [comment]
@SenHuang19 What do you think about just exporting the original model fmu, instead of writing what is essentially an empty wrapped.mo?  I've implemented suggested code in https://github.com/ibpsa/project1-boptest/pull/118.

**Comment by SenHuang19** [comment]
@dhblum The wrapped.mo may not be empty as there may be the "Modelica.Blocks.Interfaces.RealOutput"s for "out read". If we just export the original model fmu , the generated fmu is not capable with the BOPTEST APIs, right?

**Comment by dhblum** [comment]
When loaded into BOPTEST, any Modelica.Blocks.Interfaces.RealOutput or Modelica.Blocks.Interfaces.RealInput in the generated FMU will still be recognized by BOPTEST, and actually available for reading/writing.  However, the default value of inputs will be 0 (unless otherwise specified with a start value in the model), they will not be associated with an activate/deactivate signal, and the outputs will not be linked to any KPI calculations.

**Comment by SenHuang19** [comment]
@dhblum thanks for clarifying this. It is my view that it is necessary to make sure the generated FMU can be supported by all the APIs including KPIs.

**Comment by dhblum** [comment]
The only issue I see here with the BOPTEST API is that using the ``parser.py`` to compile a Modelica model with no signal exchange blocks into an FMU will generate an empty ``kpis.json`` file.  If this empty ``kpis.json`` is included in the testcase FMU, then the ``/kpi`` API call fails because there are no outputs specified to calculate the core KPIs.  That is why I said if no signal exchange blocks are used AND the user wants to still calculate core KPIs using FMU outputs defined in their own way, the content of the ``kpis.json`` needs to be generated a different way.

Granted, if the ``/kpi`` API call finds an empty or otherwise improperly formatted ``kpis.json``, it should return an appropriate message to the user, instead of just failing.  But that can be handled in a separate issue I think.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/118.
