### ISSUE TITLE
Error in specifying zone for data management

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#121]
This issue is to address an error in the data manager when specifying specific zone for internal gains, occupancy, and setpoint schedules.  

For example, if the column name is ``LowerSetp[zon]``, then the following error is encountered when trying to compile the FMU with the data manager:

```
Traceback (most recent call last):
  File "compile_fmu.py", line 23, in <module>
    fmupath = compile_fmu()
  File "compile_fmu.py", line 18, in compile_fmu
    fmupath = parser.export_fmu(modelpath, [mopath])
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/parsing/parser.py", line 198, in export_fmu
    man.save_data_and_kpisjson(fmu_path=fmu_path)
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/data/data_manager.py", line 136, in save_data_and_kpisjson
    self._append_csv_data() 
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/data/data_manager.py", line 85, in _append_csv_data
    if appended[key] is not None:
KeyError: 'LowerSetp[zon]'
```

The fix for the error is to instead specify  the column name as ``LowerSetp``.  However, this does not allow for data specific to individual zones, which may be the case in multi-zone buildings.

The suggested fix is for the data manager to look for column names with ``LowerSetp`` in them, instead of explicitly with that name.  This may have consequences downstream with data retrieval that would have to be fixed as well.  @JavierArroyoBastida What do you think?

UPDATE [12/3/2019]:  Add to-do list based on @JavierArroyoBastida below comments and further discussion:
- [x] Add a parameter for specifying a zone designator to the read Modelica signal exchange block if KPI designators of ``AirZoneTemperature`` or ``OperativeZoneTemperature`` or ``RadiativeZoneTemperature`` are chosen.  UPDATE [2/23/2020]:  Being addressed in https://github.com/ibpsa/modelica-ibpsa/pull/1295.  UPDATE [3/4/2020]:  https://github.com/ibpsa/modelica-ibpsa/pull/1295 has been closed.
- [x] Edit the parser to read the zone designator and appropriately generate kpis.json such that the zone designator is appended to the appropriate KPI keyword for ``AirZoneTemperature``, ``OperativeZoneTemperature``, and ``RadiativeZoneTemperature``.  UPDATE [2/23/2020]:  Added in https://github.com/ibpsa/project1-boptest/commit/000bade2ede8c3f76ab59161b73421099cba5fc0 and tested in https://github.com/ibpsa/project1-boptest/commit/c6a4edeb504b5da1fa6f9388c962609cf1fecd40.
- [x] Edit the data manager and data generator to handle zone specifiers for the categories "occupancy", "internalGains", and "setpoints".  All other category column names should remain being strictly enforced.  UPDATE [4/16/2020]: Added in https://github.com/ibpsa/project1-boptest/pull/169.
- [x] Edit the kpi calculator to loop over each zone to compute kpis in order to use the corresponding designator of each zone instead of using always the same. For instance, when calculating thermal discomfort of zone 1, the variables LowerSetp[1] and UpperSetp[1] should be used instead of LowerSetp and UpperSetp.  UPDATE [4/16/2020]: Added in https://github.com/ibpsa/project1-boptest/pull/169.
- [x] Add unittest for multi-zone case. UPDATE [4/16/2020]: Added in https://github.com/ibpsa/project1-boptest/pull/169.
- [x] Update test case development requirements. UPDATE [4/16/2020]: Added in https://github.com/ibpsa/project1-boptest/pull/169.

**Comment by JavierArroyoBastida** [comment]
@dhblum indeed, managing data for multiple zones is going to be a challenging one. I've started up a [new branch](https://github.com/JavierArroyoBastida/project1-boptest/tree/issue121_specifyZoneForData) to show how I'd address this for the data manager. Notice that this is only a quick edit and no pull request has been made yet.

The idea is sort of what you proposed: checking if columns in data start with keys from the categories.json file. This leaves some freedom to specify a zone number at the end of the column key. This may work for loading and retrieving data using the data manager, but still some work needs to be done on the kpi calculator side. The issue there is that there needs to be a mapping between the zones of the emulator model and the loaded test case data. And for that, the following steps are needed:

- [ ] Add the possibility of specifying a zone number in the enumeration of the read Modelica block.
- [ ] Edit the kpi calculator to loop over each zone to compute kpis in order to use the corresponding variable of each zone instead of using always the same. For instance, when calculating thermal discomfort of zone 1, the variables LowerSetp[1] and UpperSetp[1] should be used instead of LowerSetp and UpperSetp. 
- [ ] The emulator developer should be aware that the zone indexes that are used in the data column keys have a correspondence with the indexes at the read blocks of the emulator model. 

I won't be able to work on this for at least two weeks from  now, but feel free to take over the branch. I'll be happy to help again once I'm back.

**Comment by JavierArroyoBastida** [comment]
@dhblum I'm writing here the conclusions from our skype meeting today:

1. A parameter in the Overwrite Modelica block is to be added to allow the specification of the zone identifier. The zone identifier may be a string of any kind, not necessarily a number. Additionally, the zone identifier parameter will only be accessable for choices of the KPI signal that may need to distinguish among different zones. This parameter will come with a default to facilitate the development of single-zone emulator test-cases or for those test-cases that do not require to differentiate among zones.

2. The parser block from BOPTEST should be able to read the new zone identifier parameter and write it down together with the signal type in the keys of the kpis.json file. 

3. A more restrictive condition is to be added when loading the test-case data. This is: only data categories that should differentiate between zones (occupancy, internalGains, setpoints) are allowed to load data columns that only start with their associated values. For all other categories, the column keys in the data files of the Resources folder need to strictly coincide with one of the values of those categories. 

4. The KPI Calculator has to be adapted to read the new format of the kpis.json keys and compute the kpis accordingly. 

We'll split up the work so that you'll take care of 1 and 2, and I'll take care of 3 and 4.  

For the unit-tests, we'll considering adding new unit-tests with a multi-zone model once we successfully pass the unit-tests that are already in place. 

Please let me know if I'm missing something.

**Comment by dhblum** [comment]
Thanks Javi, I've made an update on the initial comment of this issue to add a to-do list to track progress.  I think it has captured what you've written here.

**Comment by dhblum** [comment]
@JavierArroyoBastida I've implemented an initial version of 1. in https://github.com/ibpsa/modelica-ibpsa/tree/issue1257_zoneDesignation.  I've implemented an initial version of 2. in https://github.com/ibpsa/project1-boptest/tree/issue121_zoneDesignation.  I've done some general testing with them and think they are in pretty good shape for you to use for developing 3. and 4.  Feel free to review the implementations also and let me know if you have feedback.

**Comment by dhblum** [comment]
@JavierArroyoBastida FYI https://github.com/ibpsa/modelica-ibpsa/pull/1295 has been merged and closed.

**Comment by JavierArroyoBastida** [comment]
@dhblum thanks for the notice! I plan to work on https://github.com/ibpsa/project1-boptest/pull/133 by next week.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/169.
