### ISSUE TITLE
IBPSA/BOPTEST vs NREL/Alfalfa

### ISSUE THREAD

**Issue by MaDooSan** [ibpsa/project1-boptest#137]
Hi folks, 
Having trouble figuring out what sets IBPSA's Boptest apart from NREL's [Alfalfa](https://github.com/NREL/alfalfa). Is it the underlying simulation platform (i.e. Modelica vs. EnergyPlus/OpenStudio)? Alfalfa provides a Haystack API for controlling building points whereas Boptest seems to have a more generic API.
What are your thoughts?
Let me know if there's a more relevant forum for these discussions.

Thanks,
Madhu

**Comment by dhblum** [comment]
Hey Madhu thanks for the interest.  I'm adding Alfalfa developer @kbenne to the thread.  You've identified key differences between Alfalfa and the current BOPTEST implementation correctly.  Others are that BOPTEST calculates KPIs and provides boundary condition forecasts for testing MPC controllers.  

These started as two different projects, however have since been combined in an effort to provide a scalable solution for advanced building controls testing, with support from the U.S. DOE (see https://www.energy.gov/eere/buildings/boptest-building-operations-testing-framework).  This integration is still in process and under development.

**Comment by MaDooSan** [comment]
Thanks for the clarification @dhblum. The [development document](https://github.com/ibpsa/project1-boptest/wiki/Development-Document) was very helpful too. Looking forward to future updates!

**Comment by dhblum** [comment]
@MaDooSan Glad the documentation was helpful.  Note in https://github.com/ibpsa/project1-boptest/issues/97 we are moving it to the github repo.
