### ISSUE TITLE
Create testcase 3

### ISSUE THREAD

**Issue by JavierArroyoBastida** [ibpsa/project1-boptest#157]
This issue is to create a new testcase for unit-testing equivalent to testcases 1 and 2 but multi-zone. The purpose is to check multi-zone features in BOPTEST like the assignment of different names and set-points/thresholds to different zones. The creation of this new testcase has been triggered in https://github.com/ibpsa/project1-boptest/pull/133#issuecomment-598804397

**Comment by JavierArroyoBastida** [comment]
@dhblum what do you think of using `Buildings.Examples.HydronicHeating.TwoRoomsWithStorage` for this test case?

**Comment by dhblum** [comment]
Do you think we could accomplish the same with a multi-zone version of testcase1?  To keep it simpler for testing?  Or is it worth having a more complex case that you mention?

**Comment by JavierArroyoBastida** [comment]
@dhblum maybe keeping it simple is the best for testing indeed. testcase2 already tests a certain level of complexity. I'll come with a proposal extrapolating testcase1 to multi-zone.

**Comment by JavierArroyoBastida** [comment]
This is being addressed in https://github.com/JavierArroyoBastida/project1-boptest/tree/issue157_testcase3

**Comment by JavierArroyoBastida** [comment]
@dhblum could you have a look at https://github.com/JavierArroyoBastida/project1-boptest/tree/issue157_testcase3? the model of the new testcase3 emulates two zones: north and south, each of them is exactly the same as the one of testcase1 and therefore have the same behavior. The idea is that each zone will differ only on their set points to stress that different KPI results will come from different set point readings. If you agree with this set up I'll work on the multi-zone specification unit tests.

**Comment by dhblum** [comment]
@JavierArroyoBastida Yes I think this looks like a good initial test.  One quick change I would recommend is to change the ``zone`` parameters of the measurement blocks to be one word instead of two.  E.g. ``"North"`` and ``"South"``.  You may also make those names parameters of the model, and use those parameters in the ``zone`` parameter for each measurement tag, so the zone names are actually only defined in one place, instead of hard-coded separately in the ``TRooAir`` and ``CO2RooAir`` measurement blocks.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/169 via #121.
