### ISSUE TITLE
Event update and cs vs. me

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#213]
There is an issue with the use of Model-Exchange FMUs in BOPTEST that can lead to events not being generated properly, and incorrect results.  Thanks to Harald Walnum for initially reporting a problem with a simple test case of his.

Problem
======

Consider the following simple model, let's call it _EventExample.mo_:

<img width="791" alt="EventUpdateModel" src="https://user-images.githubusercontent.com/19480999/84905201-595f3100-b07e-11ea-830f-316947db7328.png">

Next, consider the following simulation script for the model exported as an FMU, which replicates what is done within ``testcase.py``:

```
from pyfmi import load_fmu
import numpy as np
from matplotlib import pyplot as plt

class Simulation(object):
    '''Simulation object'''

    def __init__(self,fmu_path,step,event_update):
        '''Constructor'''

        # Load FMU and options
        self.fmu = load_fmu(fmu_path)
        self.options = self.fmu.simulate_options()
        # Initialize result lists
        self.t = []
        self.y = []
        self.u = []
        # Set step and start time
        self.step = step
        self.start_time = 0
        self.final_time = self.start_time + step
        # Set event update
        self.event_update = event_update

    def advance(self,value):
        '''Advances the simulation with an input value'''

        # Set input
        time = np.array([self.start_time])
        value = np.array([value])
        input_object = (['u'], np.transpose(np.vstack((time, value))))
        # Simulate FMU
        res = self.fmu.simulate(self.start_time,
                                self.final_time,
                                options=self.options,
                                input=input_object)
        # Save results
        self.t=self.t+res['time'].tolist()
        self.y=self.y+res['y'].tolist()
        self.u=self.u+res['u'].tolist()
        # Prep for next iteration
        self.options['initialize'] = False
        self.start_time = self.final_time
        self.final_time = self.start_time + self.step
        # Event update if called
        if self.event_update:
            self.fmu.event_update()

    def plot(self):
        '''Plots results'''

        # Plot results
        plt.figure(1)
        plt.plot(self.t, self.u, label='input')
        plt.plot(self.t, self.y, label='ouput')
        plt.legend()
        plt.show()

if __name__ == '__main__':
    # Setup
    inputs = [1,3,3]
    step = 3600
    event_update = False
    fmu_path = 'EventExample_ME.fmu'
    # Simulate
    sim = Simulation(fmu_path,step,event_update)
    for i in range(len(inputs)):
        sim.advance(inputs[i])
        i=i+1
    # Plot
    sim.plot()
```

With the model exported as a Model-Exchange FMU, the following result of the three communication steps is seen.  Notice that the hysteresis, which should be triggered to TRUE at 3600 by the new input, is not.

![NoSampler_ME_NoEventUpdate](https://user-images.githubusercontent.com/19480999/84905789-236e7c80-b07f-11ea-9204-6fc9d57a3c89.png)

Diagnosis
=======

It looks like the issue is that the pyfmi master algorithm (with solver cvode) does not generate an event at the start of the 2nd simulation step.

Consider adding a sampler to the model, which can be used to generate regular time events:

<img width="782" alt="EventUpdateModel_Sampler" src="https://user-images.githubusercontent.com/19480999/84906829-7268e180-b080-11ea-9949-78b25de19a53.png">

Now, when compiling as a Model-Exchange FMU and simulating using the script, we get:
```
# Setup
inputs = [1,3,3]
step = 3600
event_update = False
fmu_path = 'EventExample_ME_Sampler.fmu'
```
![Sampler_ME_NoEventUpdate](https://user-images.githubusercontent.com/19480999/84906925-90cedd00-b080-11ea-8f1a-e17676395eea.png)

Note that changing the parameter ``sampler.samplePeriod=300`` yields:

![Figure_Sampler_300](https://user-images.githubusercontent.com/19480999/84907557-56197480-b081-11ea-97a0-f01e30690900.png)

In these cases, the use of the sampler to generate scheduled time events trigger the master algorithm to update events and change the hysteresis output.

Solution(s)
========
**One potential solution** is to add a line to the simulation script to invoke the FMU to perform an event update, using the pyfmi function ``fmu.event_update()``.  

Adding use of this function, and compiling as a Model-Exchange FMU and simulating using the script, we get:
```
# Setup
inputs = [1,3,3]
step = 3600
event_update = True
fmu_path = 'EventExample_ME.fmu'
```
![NoSampler_ME_EventUpdate](https://user-images.githubusercontent.com/19480999/84907912-cc1ddb80-b081-11ea-9b0c-51d4fc54f4fe.png)

Note that the hysteresis output is updated, though it is delayed by one communication step.

**A second potential solution** is compiling the model as a co-simulation FMU.  Doing this, and simulating using the script (without the explicit even update), we get:
```
# Setup
inputs = [1,3,3]
step = 3600
event_update = False
fmu_path = 'EventExample_CS.fmu'
```
![NoSampler_CS_NoEventUpdate](https://user-images.githubusercontent.com/19480999/84908325-549c7c00-b082-11ea-8b14-6091bd7bf8e9.png)

Note that we get the exact desired result.

Conclusion
========
**My suggestion is that by default, BOPTEST support co-simulation FMUs, and only support model-exchange at a later time if it becomes necessary.**  

**One caveat here** is that then, the number of communication points for the result output (``simulation_options['ncp']``) needs to be specified so as not to utilize a default of 500 for co-simulation FMUs (for Mode Exchange, the solver interval is used by default, which for cvode is variable).  It also needs to be a factor of the controller-model communication step size.  The value selected will affect the calculation of KPIs (due to numeric integration), and measurement outputs to test controllers, so we may need to choose something large enough to not overwhelm memory, but small enough to accurately integrate, and represent sensor measurements.  Two suggestions:

1. The number of communication points corresponds to an output interval on the order of 30s.
2. The output interval of the simulation is set small, say 1s.  These are returned to the controller, but are resampled to something more reasonable for storage in memory.  One could eventually think about allowing a test case developer to set specific sample rates for specific sensors as well, though this should be considered future work at this point in my opinion.

I encourage further discussion and thoughts by anyone.

**Comment by haraldwalnum** [comment]
Thanks again David for digging into the issue and proposing a solution. 
Regarding the simulation output interval. Would it be an idea to integrate the output inside the emulator, e.g. in the signal exchange block?
The signal can then be differentiated and possibly average in the data manager before KPI calculation. To my understanding, this should remove the issue of integration accuracy during KPI calculation.
At least for energy and flow meters, this would be closer to how they work in real life, and what you would need for output to the controllers. For indoor climate sensor, you probably want the value at the end of the control step.

**Comment by dhblum** [comment]
Thanks @haraldwalnum for the suggestion.  My one immediate concern is what to do about energy costs and carbon emission calculations, where there are weights added to the power integration that vary over time.  This could be fixed by still doing integration of these values in the KPI calculator, but applying the weight for a time step to the integrated energy consumption from the signal exchange block at that time step.

In addition, we should do some profiling to see about mitigating the memory requirements.  Some methods are suggested in https://github.com/ibpsa/project1-boptest/issues/124, though have not been fully tested yet, and definitely not with the change in approach I suggest here.

**Comment by haraldwalnum** [comment]
@dhblum. I don't see that the cost and emissions calculations should be an issue. 
Let P be the power, and Q the integrated value that is transferred from the signal exchange block:
P = der(Q)

Then within the KPI calculator:
With an output interval = dt [s], then the average power consumption between each output interval is given by:
Pavg_n = (Q_n-1 - Q_n)/dt
The Pavg time series can then be multiplied with the price or emission data.
To my opinion this should be more accurate than a numeric integration in the KPI calculator independent on output interval.

**Comment by dhblum** [comment]
@haraldwalnum I agree with your solution, which is a better description of what I was trying to suggest.  Thanks.

**Comment by JavierArroyoBastida** [comment]
Hey @haraldwalnum, @dhblum, thanks for raising and documenting the issue. 
I've been having some thoughts on it and I'm afraid I've not a solution, but maybe a suggestion: have you tried invoking `enter_event_mode()`  **before** calling `self.fmu.simulate()` within the `advance()` method? that might prepare the fmu to read event indicators right at the beginning of the simulation. If wouldn't work, maybe simply changing the solver used in pyfmi for that model? or just using a filter block on the input as pointed out by @Mathadon in our meeting yesterday?

In any case, I still advocate for the integration taking place outside of the model for different reasons: 

1. I don't think that integrating inside of the model is more efficient as it would oblige to integrate every simulation step and for every signal being read, whereas in Python integration only happens when calling the method `get_kpis()` (if needed) and only for the signals assigned for kpi calculation. Additionally, if the method proposed in https://github.com/ibpsa/project1-boptest/issues/213#issuecomment-649995162 is used, integration will happen twice: one inside the model to compute Pavg_n, and one outside the model (note that Pavg_n gets again units of Watts, not Jules, which means that integration is needed, not only simple multiplication against price or emission data). 

2. In terms of accuracy, the latter integration outside the model would still take place in the `KPI_Calculator()` and would be using Pavg_n for each output interval, instead of the full array of powers that contains the power values at the beginning and the end of the output interval (not only the average during that interval). Having the full array allows to use the trapezoidal rule for integration that we're currently using:

<img src="https://user-images.githubusercontent.com/22677958/87670632-597f4900-c770-11ea-882e-3ff9d11b6744.PNG" width="200">

whereas using the average means that we'd be limited to partition approximations:

<img src="https://user-images.githubusercontent.com/22677958/87670638-5be1a300-c770-11ea-990c-8130443bce5e.PNG" width="200">

3. Finally, for IBPSA Project 1 only modelica Models are used, but BOPTEST is meant to be compliant with the more general pyfmi standard so that the possibility remains for the integration of models coming from other languages. Integrating in Modelica would make the IO blocks certainly more complicated (think for instance integration of discomfort which is not simple integration but integration of signals out of a range), leading to potential divergence on the way kpis are computed. On the contrary, integrating in Python allows to have a unique class where kpis are unambiguously defined.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida for the reply.  Just a couple of notes:

1. Tried ``enter_event_mode()`` but got ``pyfmi.fmi.FMUException: Failed to enter event mode.``

2. Adding a filter indeed leads to the desired result as ME FMU.  @haraldwalnum Can you test in your test case with a filter as shown?

Model: 
<img width="929" alt="Screen Shot 2020-07-29 at 11 52 30 AM" src="https://user-images.githubusercontent.com/19480999/88823634-4f5b4280-d193-11ea-8bdc-5facac4b3673.png">

Result:
![Figure_1-6](https://user-images.githubusercontent.com/19480999/88823671-55e9ba00-d193-11ea-9ed3-0c95635a8996.png)

**Comment by haraldwalnum** [comment]
Thanks @JavierArroyoBastida and @dhblum.
Applying the filter before the hysteresis in the models seems to give the desired results. So that's a good solution for me!

I guess this solution avoids the issue with output interval and integration inside or outside the model...
However Javier, I am not sure I agree with your point 2. Since P_avg_n is the true average, calculated from the integrated value, multiplying it with dt, will bring you back to the actual integrated value (consumed energy).
I totally agree that such approach is mainly suited for energy related KPIs (energy, cost and emissions).

**Comment by dhblum** [comment]
Thanks @haraldwalnum for the update!  Glad it works.  This does avoid the downstream issues related to supporting only co-simulation FMUs.  I will close this issue for now.
