### ISSUE TITLE
Make examples easier to use and fix bug

### ISSUE THREAD

**Issue by FWuellhorst** [ibpsa/project1-boptest#328]
Besides the following minor bug (python 3.8), the example for testcase1 works fine:
Line: 
`points = measurements.keys() + inputs.keys()`
should be 
`points = list(measurements.keys()) + list(inputs.keys())`, at least in python 3.8. In python 2.X, both lines work.

Additionally, users could skip one step if the file would start with 
```python
import sys
import pathlib
sys.path.insert(0, str(pathlib.Path(__file__).absolute().parents[2]))
import requests
import numpy as np
from examples.python.custom_kpi import custom_kpi_calculator as kpicalculation
```
instead of 
```python
import requests
import numpy as np
from examples.python.custom_kpi import custom_kpi_calculator as kpicalculation
```

I would be happy to open a pull request with listed changes and check if other python examples are affected as well.
If the solutions don't align with the project, feel free to close the issue.

**Comment by JavierArroyoBastida** [comment]
@FWuellhorst I like the edit to have the example working with both python 3.8 and 2.x. A PR will be very welcome for that. Note that you can check if changes affet to other examples and modules in general by running the unit tests locally using the `make test_all` command in the testing directory. This takes quite long (one hour or so) but ensures that all other functionality is not affected. If you are sure that your changes are only affecting one module then you can check only that specific part by calling one of the following:
```
make test_parser
make test_data
make test_forecast
make test_kpis
make test_testcase1
make test_testcase2
make test_testcase3
make test_bestest_air
make test_bestest_hydronic
make test_bestest_hydronic_heat_pump
make test_multizone_residential_hydronic
```
The Travis tests will always run all tests anyways.

I'm not sure the other edit is required though since the examples assume that those directories can already be found by the environment.

**Comment by FWuellhorst** [comment]
Ok, perfect! I will try the tests out. Thanks for the information. I will create a PR soon.

Regarding the PYTHONPATH: Yes, I know the tutorial and ReadMe include this step. The change could be a possible enhancement to reduce the number of steps necessary to test BOPTEST. However, as users have to install docker, setting the PYTHONPATH should not be a problem.

**Comment by dhblum** [comment]
Agreed, thank you @FWuellhorst!  One question is if ``sys.path.insert(0, str(pathlib.Path(__file__).absolute().parents[2]))`` edits the PYTHONPATH permanently or just for as long as the process runs?

Also there's some discussion and changes discussed here for Python 3 support: https://github.com/ibpsa/project1-boptest/issues/146.

**Comment by FWuellhorst** [comment]
@dhblum: The `sys.insert` method works only temporarily :) 
I will look it up, thanks for the info!

**Comment by dhblum** [comment]
@FWuellhorst Ok sounds good, thanks!

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/336 via #335.
