### ISSUE TITLE
Testcase failure

### ISSUE THREAD

**Issue by mildwall** [ibpsa/project1-boptest#349]
I used the JModelica docker image [docker-ubuntu-jmodelica](https://github.com/lbl-srg/docker-ubuntu-jmodelica) on Windows 10 and executed the code `$ make test_all` to run all test cases. The `test_all` command stopped during the BESTESTAir case.

>  Error at line 27, column 5, in file 'BESTESTAir/BaseClasses/Thermostat_T.mo':
    Cannot find component declaration for reverseActing

I also checked the testing_report.txt, and there are failure messages from testcase1 and testcase 2.

> From test_testcase1.py
    =========================
    Of 27 tests run...
    Passed: 26
   Failures: 1
    Errors: 0
    Failure Messages
     ----------------
    Failure 0:
    Traceback (most recent call last):
      File "[my-modelica-path]\project1-boptest\testing\test_testcase1.py", line 139, in test_run
        self.compare_ref_values_df(df, ref_filepath)
      File "[my-modelica-path]\project1-boptest\testing\utilities.py", line 245, in compare_ref_values_df
        self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
    AssertionError: False is not true : Max error (0.0045330832967604) in trajectory greater than tolerance (0.001) at index 0. y_test: 0.0051163471062426, y_ref:0.0005832638094822 Key is time_rat.

>From test_testcase2.py
    =========================
     Of 20 tests run...
     Passed: 19
     Failures: 1
     Errors: 0
     Failure Messages
     ----------------
    Failure 0:
   Traceback (most recent call last):
     File "D:\CGK\Documents\Dymola\project1-boptest\testing\test_testcase2.py", line 111, in test_run
       self.compare_ref_values_df(df, ref_filepath)
     File "D:\CGK\Documents\Dymola\project1-boptest\testing\utilities.py", line 245, in compare_ref_values_df
       self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
    AssertionError: False is not true : Max error (0.0054901482385618) in trajectory greater than tolerance (0.001) at index 0. y_test: 0.0061856865703507, y_ref:0.0006955383317889 Key is time_rat.

**Comment by dhblum** [comment]
I do not expect ``$ make test_all`` to pass all tests if run within the JModelica Docker container.  The unit tests are meant to be run in an environment defined by the ``travis.yml`` file, and also with use of a specific Docker container (defined by ``testing/Dockerfile``) based on the JModelica Docker image but also including the specific versions of each dependent Modelica library required for compiling and unit testing each test case.

Therefore, the error in the BESTESTAir unit test is likely due to an incorrect Modelica Buildings Library version being used and the errors (very small numeric differences) from testcase1 and testcase2 unit tests are likely due to Python 2 vs 3, or other differences in Modelica library or Python package versions.

**Comment by dhblum** [comment]
@mildwall I believe this can be closed per my comment above.  Please let me know if not and why.

**Comment by mildwall** [comment]
@dhblum Thank you for your clarifying. I close this issue now.

**Comment by dhblum** [comment]
@mildwall Great, thank you!
