### ISSUE TITLE
multizone_office_simple_air boundary condition questions - roof and floor?

### ISSUE THREAD

**Issue by epaulson** [ibpsa/project1-boptest#418]
This might be a dumb question and if so I apologize, but I've been trying to wrap my head around the multizone_office_simple_air (MOSA) testcase and understanding how it fits into the outside world. 

I understand that it's based on the DOE Reference Buildings, specifically the Chicago O'Hare setting. I downloaded the IDF file for that building - it's a 3 story building with a roof and a floor slab, and each floor is a large core area with 4 narrower zones around it, the N/E/S/W zones. The exterior walls are 1/3 windows. You can kinda see all of that in this visualization of the IDF file:

<img width="1418" alt="Screen Shot 2022-04-19 at 3 43 35 PM" src="https://user-images.githubusercontent.com/315267/164093215-8dc01227-f53c-4cf0-82b0-a3c8a2a58668.png">

I further understand that the BOPTEST testcase is not actually that IDF file, but is a 1-floor version of that space. The BOPTEST testcase is in turn using the code from the [modelica-buildings VAVReheat](https://github.com/lbl-srg/modelica-buildings/tree/master/Buildings/Examples/VAVReheat) example, with some "method overriding" in the BOPTEST testcase to implement some additional control, so to follow the simulation completely you have to read the code from both the BOPTEST testcase and the Modelica-buildings library. (I think - this is probably at the root of my question - I'm still very much a newbie when trying to read and follow Modelica code)

I'm having some trouble finding in the BOPTEST/Modelica-buildings library code exactly what's happening at the floor boundaries above and below the "one floor" building. If there's a roof defined I haven't found it, and similarly if there's a ground slab defined, I haven't found that either. Again, it's totally possible I've just missed them.

I'm unclear if the BOPTEST Testcase is simulating a 1 story building with a roof and floor, with the same dimensions as one floor of the DOE Reference building, or if the BOPTEST testcase is simulating 1 floor of the 3 story building, and is just ignoring what's happening at the floor and ceiling boundary of that floor with respect to what's happening on the other floors, since the windows and outside air exchange are probably interesting enough without worrying about anything else. 

Again, this is probably a dumb question and maybe isn't a distinction worth making, but it's gnawing at me trying to understand what matters in Modelica-buildings/BOPTEST and what can be ignored for the bigger picture.

**Comment by mwetter** [comment]
@epaulson : The VAVReheat model in the Modelica Buildings Library models _one_ story of an office building that has multiple stories. The floor and boundary conditions of the modeled story are set up in such a way that the story above and below the modeled story has the same terminal conditions. Hence, in this model, there is no slab that faces the ground, and no roof that faces the outside. You can think of it as a high building in which each story has exactly the same conditions, and the first and top floor is neglected.

**Comment by dhblum** [comment]
@epaulson Just to followup.  The BOPTEST test case indeed inherits the envelope model from the Buildings library that you point out and @mwetter describes.  So, the envelope model is more like your indication "the BOPTEST testcase is simulating 1 floor of the 3 story building" except that it is not ignoring what happens at the ceiling and floor, it is assuming that what happens in the floor above and below our floor of interest is the same as our floor of interest.

I propose adding to the documentation of the BOPTEST case a description for clarifying this, and also propose adding a floor plan diagram since the 5-zone core-perimeter layout many building scientists/engineers may recognize as the DOE reference layout probably is not known to non experts or generally those not familiar.

Ideally, users should not need to inspect the Modelica model to understand the test case.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/430.
