### ISSUE TITLE
Boptest Dashboard Url

### ISSUE THREAD

**Issue by tijcolem** [ibpsa/project1-boptest#435]
Currently the boptest dashboard url is defined as env that is injected into the worker container at runtime. 

The app picks it up here: 
https://github.com/ibpsa/project1-boptest/blob/boptest-service/worker/jobs/boptest_run_test/job.py#L215

The api key that is used to send results to the dashboard api is part of the json payload of the project. 

https://github.com/ibpsa/project1-boptest/blob/boptest-service/worker/jobs/boptest_run_test/job.py#L227

I'm not sure if there is a use case here, but if there are multiple dashboards it may make sense to include the dashboard url as part of the json payload like the api key.  The client would set both url and api key.  The user needs to register an account on the boptest dashboard so the url end point would be known to the user.

**Comment by dhblum** [comment]
@tijcolem I chatted a bit with @kbenne about this too.  Thanks for raising.   I think it is best for now to keep the url as an environment variable, so that the basic assumption by users is that there is one dashboard associated with our deployed web-service and our official core BOPTEST software releases.  If additional dashboards need to be deployed for specific reasons, their administration and access via other BOPTEST services can be considered at that time.  

Let me know if you have additional comments, otherwise, I suggest closing this issue.

**Comment by dhblum** [comment]
Closing via #403.
