### ISSUE TITLE
Abstract test case input output lists in unit tests

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#463]
This is to abstract the definition of input and output lists within if-else statements in the API unit tests in ``utilities.py`` to the ``setUp`` method in each test cases's specific testing file ``test_<testcase>``.  For example in these locations:

- https://github.com/ibpsa/project1-boptest/blob/master/testing/utilities.py#L565
- https://github.com/ibpsa/project1-boptest/blob/master/testing/utilities.py#L689
- https://github.com/ibpsa/project1-boptest/blob/master/testing/utilities.py#L716
- https://github.com/ibpsa/project1-boptest/blob/master/testing/utilities.py#L865

**Comment by dhblum** [comment]
Assign @EttoreZ.

**Comment by EttoreZ** [comment]
I will make a pull request on the branch Issue463_abstract_testcase_inout_lists_unittests

**Comment by EttoreZ** [comment]
I made the pull request, I only have one comment:
In the script  `utilities.py` function `test_advance_false_overwrite`, the input used for `bestest_hydronic` is different than in function `test_invalid_advance_value`, namely `u = {'oveTSetSup_activate': 0, 'oveTSetSup_u': 273.15+60,              'ovePum_activate': 0,'ovePum_u': 1}` and `u = {'oveTSetSup_activate': 0, 'oveTSetSup_u': 273.15+60,'ovePum_activate': 0}`. In the pull request I used the first input dictionary and running the tests passed all of them, since the actual values or number of inputs do not matter for those specific unit test.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/472.
