### ISSUE TITLE
Unit tests depends on list order that is not determintistic

### ISSUE THREAD

**Issue by kbenne** [ibpsa/project1-boptest#529]
This line and the very next one depends on a determinisitic order of object keys

https://github.com/ibpsa/project1-boptest/blob/b040c4283476ba3e7db76d70d43c789946ff3627/testing/utilities.py#L604

While testing BOPTEST-Service I discoverd this test failing due to the nondeterminism. (Service appears to be sending the keys back in the oposite order) I think the test should not assume a particular order.

https://stackoverflow.com/questions/42232200/as3-deterministic-json-string-from-an-object

@dhblum

**Comment by dhblum** [comment]
Thanks for pointing out @kbenne.  I agree, and see it's because of ``forecast_points[0]`` in the next line 605.  I suggest updating to specify the one point to fetch in the test setup for each test case as is already done for singular input and measurement checks, for example as in https://github.com/ibpsa/project1-boptest/blob/b040c4283476ba3e7db76d70d43c789946ff3627/testing/test_bestest_air.py#L54.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/530.
