### ISSUE TITLE
Missing model inputs for BESTEST Air

### ISSUE THREAD

**Issue by Swopper050** [ibpsa/project1-boptest#555]
I just discovered the package (awesome btw!) and I was running a little test with the BESTEST Air test case, however, it did not respond to my change in heating setpoint.

These are the four model inputs shown in the detailed description:
The model inputs are:
* `fcu_oveTSup_u` [K] [min=285.15, max=313.15]: Supply air temperature setpoint
* `fcu_oveFan_u` [1] [min=0.0, max=1.0]: Fan control signal as air mass flow rate normalized to the design air mass flow rate
* `con_oveTSetHea_u` [K] [min=288.15, max=296.15]: Zone temperature setpoint for heating
* `con_oveTSetCoo_u` [K] [min=296.15, max=303.15]: Zone temperature setpoint for cooling

However, when looking closer at the response, I also saw `con_oveTSetHea_activate`, which needed to be 1.0 in order for the model to respond to the change in setpoint.

Shouldn't these also be documented? Or did I miss them somewhere?

Same for:
* `con_oveTSetCoo_activate`
* `fcu_oveFan_activate`
* `fcu_oveTSup_activate`

**Comment by dhblum** [comment]
The need for using the associated activation signals is specified here in the README: https://github.com/ibpsa/project1-boptest#test-case-restful-api on the third bullet point under "Example RESTful interaction."  I agree this has become buried too deep since early development when the README was simpler and the primary documentation piece.  Thank you @Swopper050  for pointing out.

I suggest adding the activate signals to the test case documentation, and also a more detailed description in /advance API description in the README and User Guide.

**Comment by dhblum** [comment]
@EttoreZ Can you address this?  I suggest updating https://github.com/ibpsa/project1-boptest/blob/master/data/get_html_IO.py to also write the input point ``<point_name>_activate`` for each input point, and a description "Activation signal to overwrite <point_name_u> where 1 activates, 0 deactivates (default)".  And then run that script for each test case to generate new docs.

**Comment by EttoreZ** [comment]
@dhblum I updated the `get_html_IO.py` script and all test cases documenations. The PR is ready for review.
