### ISSUE TITLE
Controller in testcase "bestest_hydronic

### ISSUE THREAD

**Issue by CCCGao** [ibpsa/project1-boptest#568]
In this testcase, the pump can switch on or off based on indoor temperature with the heating setpoint. But in the baseline, the pump keeps running all the time because the u_high in the model is set to 24°C, which can not reach. Is this u_high set too high?

**Comment by EttoreZ** [comment]
Hey @CCCGao, I am sorry for the late reply. 24°C is meant to be the cooling setpoint. According to the logic the pump turns on when the internal temperature goes below `uLow` and turns off only if cooling setpoint `uHigh` is reached. 
The baseline control logic for the pump is rather conservative. @dhblum  was there any discussion on this topic?

**Comment by dhblum** [comment]
I have a note in the review document for this emulator "Common in Europe to have constant circulation pump for radiator."  The control was modeled after a house in Belgium, which I personally don't have much experience with a typical set up.  Does the temp reach uHigh in summer time and turn off the pump eventually?

**Comment by EttoreZ** [comment]
Below is an image with the results for the whole year:
- The pump does shut off when `uHigh` goes above 24°C.
- It is a bit peculiar that the heating system turns on in the Summer, which is probably due to the fact that the controller is set in heating mode using `con.revert` parameter for the whole year.
<img width="1493" alt="image" src="https://github.com/ibpsa/project1-boptest/assets/46685675/a1b82f84-8385-4f9d-955c-e7c13dcf0cc1">

**Comment by EttoreZ** [comment]
@dhblum  that sounds good. I consider this issue closed then.
