### ISSUE TITLE
is there something wrong with the document of bestest_air?

### ISSUE THREAD

**Issue by cosmos0x57** [ibpsa/project1-boptest#658]
hello, I try to use bestest_air to do a control test. I find that the "con_oveTSetCoo_u"(Zone temperature setpoint for cooling
) is from 296.15K to 303.15K. It seems that this zone temperature setpoint cannot cooling the office building sufficiently, for the thermal comfort zone is 294.15K-297.15K. The zone temprature setpoint seems too high. While the "con_oveTSetHea_u"(Zone temperature setpoint for heating) is from 288.15K-296.15K, it seems too low for heating.

Another question is that the cooling peak period is from Day 282 to Day 296, but the outside temperature in this period is only about 288.15K at noon, while the outside temperature is over 303.15K at noon in July. Why lower outside temperature day cause a higher cooling load?

**Comment by EttoreZ** [comment]
Dear @cosmos0x57, thank you for reaching out with your questions. I am not sure I understand the first question. The figure below shows in black dashed the setpoint and setback temperature for heating and cooling that create the comfort band. The highlighted areas in blue and red instead are limits for `con_oveTSetCoo` and `con_oveTSetHea`, and can be used to have a stricter or looser comfort boundary with respect to the default.
<img width="641" alt="image" src="https://github.com/user-attachments/assets/3e4caac7-2ca1-4807-987e-c45fd8989b72">

For the second question the peak cooling period is calculated as: "The two-week period is centered on the day with the maximum 15-minute system cooling load in the year". As you can see from the figure below, the peak cooling day is 289. Now as for why that day has higher load than some days in July, temperature only plays a part in that, since it depends also on radiation, internal gains and control. Using a different definition such as cooling degree days would lead to a different peak cooling period.

<img width="2033" alt="image" src="https://github.com/user-attachments/assets/03885eff-4310-41ba-9eeb-cebcc894a96c">

**Comment by cosmos0x57** [comment]
Regarding question one: Typically, in the cooling season, the temperature setpoint is the minimum value for indoor air temperature theoretically. Therefore, if I set the temperature setpoint to 296.15K under the current conditions, the indoor air temperature will be no lower than 296.15K, and will not fall within the 294.15K-296.15K range. Consequently, the comfort range of 294.15K-296.15K seems to be meaningless. Hence, should we consider setting a lower limit for the temperature setpoint?

**Comment by EttoreZ** [comment]
dear @cosmos0x57, thank you for the further comment. What you suggest is reasonable and hence I created a new pull request [issue658_UpdateMinMaxLimits](https://github.com/ibpsa/project1-boptest/tree/issue658_UpdateMinMaxLimits), where I will update all the limits of control variables by having `min` and `max` only constrained by "physics" or "operational constraints". In the case of bestest air `con_oveTSetCoo` and `con_oveTSetHea` will be updated so that the setpoints can be between 288.15 and 303.15.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/694.
