### ISSUE TITLE
For the service implementation, invalid input names to `advance` do not return 400 as expected.

### ISSUE THREAD

**Issue by kbenne** [ibpsa/project1-boptest#671]
For example, see the test named `test_invalid_advance_name` located [here](https://github.com/ibpsa/project1-boptest/blob/7deb826ce27b528a1bf0721fbb8a1424086ebc4d/testing/utilities.py#L853). When testing the service implementation of BOPTEST, this test will fail because a 200 response is returned even if the input name is not valid.

**Comment by kbenne** [comment]
This stems from a subtlety in the format of the request.

I discovered that (when using the service implementation) advancing a simulation with `{'invalid': 0}` will trigger the test failure, however if the payload is modified to pass 0 as a string `{'invalid': '0'}`, then the test will pass. 


I discovered that the service implementation is (I think correctly) passing the json payload through the web service API into testcase.py unaltered. That is, if the client passes a numeric value through the API, then a numeric value will be sent to the advance method within Testcase (aka testcase.py). Conversely, if the client sends a string, then indeed a string is passed into Testcase.advance. I believe that the non service implementation of BOPTEST has been cohersing the client's numeric input into a string even if it was sent as a numeric value. I believe the service implementation is doing the more correct thing here, as it is probably more efficient and likely saves precision, although I suppose it is debatable.

Knowing this difference in behavior we have to inspect `Testcase.advance`. The root cause of the issue is [here](https://github.com/ibpsa/project1-boptest/blob/7deb826ce27b528a1bf0721fbb8a1424086ebc4d/testcase.py#L278). In our test example, we send `{'invalid': '0'}`. The numeric value `0` is evaluated as false by the linked code and therefore (if this is the only input) the `written` flag will be false. (The idea being that there is an invalid input name, but it is not "written" and therefore the subsequent validation does not happen.) On the other hand sending `'0'` will resolve as true, the "written" flag will be set, and input validation will occur.

The original test failure may be a (fortunate) accident. I think if any value other than 0 were selected *or* there were other valid input, then the test would pass. Nevertheless this is a bonified issue that needs attention and I think the correct fix should be in the lines of testcase.py linked above.

@dhblum

**Comment by dhblum** [comment]
Thanks alot @kbenne for looking into this.  This is an issue that needs to be corrected in testcase.py, specifically that line 278, and test design.I think it's an issue that's not only only uncovered because of the test design (single key with a value of 0), but also is only actually relevant to the specific test and not an issue for expected usage.  Users are required to supply a pair of ``_u`` and ``_activate`` key values and in order to activate the overwrite for any control signal.  In that, the ``_activate`` key needs to be set to 1 (which would trigger the ``written`` flag), otherwise the overwrite will not happen.  So, sending a single ``_u`` key with a value of 0 should not overwrite anything anyway, nor should any number of pairs where both the ``_u`` and ``_activate`` keys are 0 for all pairs.  

In terms of a fix, that check in line 276-280 may be outdated at this point with the more fine-tuned checks in 286-324, which I believe were introduced later, and should filter out invalid (i.e. ``none``) or empty key values, which the check in 278 I think was originally meant to filter for.  I will do some further testing to make sure, revise the test design, and submit a PR with changes.

**Comment by dhblum** [comment]
Fixed by https://github.com/ibpsa/project1-boptest/commit/cae82e02b4e8fba80faa7302791c29d7a6019b1a, tests passing in https://app.travis-ci.com/github/ibpsa/project1-boptest/builds/272027799.

**Comment by kbenne** [comment]
👍
