### ISSUE TITLE
Occupancy schedule BESTEST Hydronic Heat Pump

### ISSUE THREAD

**Issue by JonasHillenGit** [ibpsa/project1-boptest#695]
When looking in Dymola in the IDEAS.Examples.IBPSA.SingleZoneResidentialHydronic model, an error is present in the occupancy schedule. It states: "The zone is occupied by 5 people before 7 am and after 8 pm each weekday and full time during weekends." However, when looking at the occupency schedule in Dymola, it shows occupancy after 7 pm instead of 8 pm, which is incorrect. You can see this in the screenshot provided below. This should be either corrected in the schedule description or in the model of the BESTEST Hydronic Heat Pump.

![error](https://github.com/user-attachments/assets/a2093d8b-0130-4b40-a513-1ce22e6b078b)

**Comment by EttoreZ** [comment]
Hi @JonasHillenGit, thank you for pointing out the discrepancy! I think updating the documentation to make it consistent with the actual implementation would make more sense. @dhblum I think this could be easily incorporated into the min max PR #694 addressing issue  #658. If you give me the green light I can make the change.

**Comment by dhblum** [comment]
Thanks for reporting @JonasHillenGit.  @EttoreZ Sounds like a good plan, please go ahead and make the fix.

**Comment by EttoreZ** [comment]
@JonasHillenGit I double checked and looking at output  (see screenshot) it looks like in the description with occupancy "before 7 am and after 8 pm".
<img width="606" alt="image" src="https://github.com/user-attachments/assets/70abea6e-6cb7-430d-980b-9717722726b9">
Digging a bit it's because even though `yOcc` is a RealExpression, it uses `IDEAS.Utilities.Time.CalendarTime` in the expression, which is an `Integer variable`, therefore the expression `calTim.hour > 19` give the correct output and occupancy starts at 8 pm. This is also true for `bestest_hydronic` since they share the same schedule.  @JonasHillenGit let me know if it solves your issue so I can close it.

**Comment by JonasHillenGit** [comment]
@EttoreZ Thank you for checking it! Just wanted to be sure this was no mistake. The issue can be closed.

**Comment by EttoreZ** [comment]
@dhblum I am closing this issue, since it was solved. Hence there is no need make any changes to #694, which is ready for review.

**Comment by dhblum** [comment]
Sounds good, thank you.
